import zipfile

# دیکشنری کامل فایل‌ها و ترجمه‌های آن‌ها
translations = {
    "moves_chairtwistextended_to_chairtwistbind.txt": "دست‌ها را قفل کنید / قفل (بایند) را بگیرید.",
    "moves_childwide_to_boxneutral.txt": "خود را بالا بکشید و به وضعیت چهار دست و پا (باکس) بروید.",
    "moves_childwide_to_childwidesidelean_2_l.txt": "به سمت چپ متمایل شوید.",
    "moves_childwide_to_childwidesidelean_2_r.txt": "به سمت راست متمایل شوید.",
    "moves_childwide_to_childwidesidelean_l.txt": "تمام وزن را به سمت چپ منتقل کنید.",
    "moves_childwide_to_childwidesidelean_r.txt": "تماماً به سمت راست متمایل شوید.",
    "moves_childwidesidelean_to_childwide.txt": "به مرکز (وضعیت اولیه) بازگردید.",
    "moves_childwidestart_to_childwide.txt": "تمرین خود را با قرار گرفتن در وضعیت کودک باز (Wide Child's Pose) آغاز کنید.",
    "moves_corpse_to_bridge.txt": "به وضعیت پل (Bridge Pose) بالا بیایید.",
    "moves_corpse_to_corpsedoublelegraise.txt": "به وضعیت تجدید قوا بروید.",
    "moves_corpse_to_wheel.txt": "به وضعیت چرخ کامل (Full Wheel Pose) بالا بیایید.",
    "moves_corpsedoublelegraise_to_corpse.txt": "پاهای خود را پایین بیاورید.",
    "moves_corpsedoublelegraise_to_shoulderstandsupported.txt": "پاهای خود را کاملاً به بالا بکشید و به وضعیت ایستادن روی شانه (Shoulder Stand) بروید.",
    "moves_crow_to_crowflying_l.txt": "پای چپ خود را به سمت بیرون بکشید.",
    "moves_crow_to_crowflying_r.txt": "پای راست خود را به سمت بیرون بکشید.",
    "moves_crow_to_seatedonheelshandsonmatopenedknees.txt": "بازگردید.",
    "moves_downwarddog_to_boxneutral.txt": "زانوها را پایین بیاورید و به حالت چهار دست و پا بروید.",
    "moves_downwarddog_to_downwarddogbentknees.txt": "زانوهای خود را خم کرده و به جلو نگاه کنید.",
    "moves_downwarddog_to_downwarddogbentknees_2.txt": "زانوهای خود را خم کنید.",
    "moves_downwarddog_to_downwarddoghandtoankle_l.txt": "دست چپ خود را به سمت بیرون مچ پای راست ببرید.",
    "moves_downwarddog_to_downwarddoghandtoankle_r.txt": "دست راست خود را به سمت بیرون مچ پای چپ ببرید.",
    "moves_downwarddog_to_downwarddoglegup_2_l.txt": "پای چپ خود را بالا بیاورید.",
    "moves_downwarddog_to_downwarddoglegup_2_r.txt": "پای راست خود را بالا بیاورید.",
    "moves_downwarddog_to_downwarddogontoes.txt": "روی پنجه‌های پا بلند شوید.",
    "moves_downwarddog_to_plank.txt": "به وضعیت پلانک (Plank Pose) بروید.",
    "moves_downwarddog_to_plankkneeling.txt": "به وضعیت پلانک روی زانوها بروید.",
    "moves_downwarddogbentknees_to_forwardbend_float.txt": "به سمت جلو شناور / روان حرکت کنید.",
    "moves_downwarddogbentknees_to_forwardbend_step_2.txt": "به جلو گام بردارید.",
    "moves_downwarddogbentknees_to_forwardbend_step_l.txt": "پای چپ را به جلو بگذارید؛ پای پشتی به دنبال آن می‌آید.",
    "moves_downwarddogbentknees_to_forwardbend_step_r.txt": "پای راست را به جلو بگذارید، پای پشتی به دنبال آن می‌آید.",
    "moves_downwarddogbentknees_to_lunge_l.txt": "پای چپ خود را به جلو و بین دستانتان بگذارید.",
    "moves_downwarddogbentknees_to_lunge_r.txt": "پای راست خود را به جلو و بین دستانتان بگذارید.",
    "moves_downwarddogbentknees_to_lungekneeling_2.txt": "به جلو گام بردارید و زانو را پایین بیاورید.",
    "moves_downwarddoghandtoankle_to_downwarddog.txt": "آن را به مرکز بازگردانید.",
    "moves_downwarddogkneetoforehead_to_planklegup.txt": "به وضعیت پلانک خود بروید.",
    "moves_downwarddogkneetoforehead_to_planklegup_pushup.txt": "یک حرکت شنا (Push-up) انجام دهید.",
    "moves_downwarddoglegup_to_downwarddog_l.txt": "پای چپ را پایین بیاورید.",
    "moves_downwarddoglegup_to_downwarddog_r.txt": "پای راست را پایین بیاورید.",
    "moves_downwarddoglegup_to_downwarddoglegupstackhips_l.txt": "لگن را تراز کنید و زانوی چپ را خم کنید.",
    "moves_downwarddoglegup_to_downwarddoglegupstackhips_r.txt": "لگن را تراز کنید و زانوی راست را خم کنید.",
    "moves_downwarddoglegup_to_lunge_2_l.txt": "پای چپ را به جلو عبور دهید.",
    "moves_downwarddoglegup_to_lunge_2_r.txt": "پای راست را به جلو عبور دهید.",
    "moves_downwarddoglegup_to_lungehandsonmatflying.txt": "به وضعیت مرد پران (Flying Man) بروید.",
    "moves_downwarddoglegup_to_planklegup.txt": "آن را به حالت پلانک ببرید.",
    "moves_downwarddoglegup_to_planklegupkneeling_l.txt": "به پلانک بروید و زانوی راست را پایین بیاورید.",
    "moves_downwarddoglegup_to_planklegupkneeling_r.txt": "به پلانک بروید و زانوی چپ را پایین بیاورید.",
    "moves_downwarddoglegupstackhips_to_downwarddoglegup.txt": "پا را صاف کنید.",
    "moves_downwarddoglegupstackhips_to_wheelflip_2.txt": "بچرخید و به وضعیت چرخ بروید.",
    "moves_downwarddogontoes_to_downwarddog.txt": "پاشنه‌های خود را روی زمین بگذارید.",
    "moves_downwarddogontoes_to_downwarddoghamstring_2_l.txt": "پاشنه چپ پایین.",
    "moves_downwarddogontoes_to_downwarddoghamstring_2_r.txt": "پاشنه راست، پایین.",
    "moves_downwarddogontoes_to_downwarddoghamstring_l.txt": "پاشنه چپ را پایین بیاورید؛ زانوی راست خم می‌شود.",
    "moves_downwarddogontoes_to_downwarddoghamstring_r.txt": "پاشنه راست را پایین بیاورید؛ زانوی چپ خم می‌شود.",
    "moves_downwarddogstart_to_downwarddog.txt": "به وضعیت سگ سر پایین بروید.",
    "moves_featheredpeacock_to_dolphin.txt": "به وضعیت دلفین پایین بیایید.",
    "moves_forwardbend_to_forwardbendhalfway.txt": "قفسه سینه را تا نیمه بالا بکشید.",
    "moves_forwardbend_to_lunge_l.txt": "پای راست را به عقب بگذارید و به حالت لانج بروید.",
    "moves_forwardbend_to_lunge_r.txt": "پای چپ را به عقب بگذارید و به حالت لانج بروید.",
    "moves_forwardbend_to_lungekneeling_2_l.txt": "پای راست به عقب، زانو روی زمین.",
    "moves_forwardbend_to_lungekneeling_2_r.txt": "پای چپ به عقب، زانو روی زمین.",
    "moves_forwardbend_to_mountainarmsup.txt": "از مرکز بدن به بالا بکشید و به وضعیت کوه بروید طوری که بازوها کنار گوش‌ها باشند.",
    "moves_forwardbend_to_mountainarmsup_2.txt": "دست‌ها را بالا بکشید.",
    "moves_forwardbenddeep_to_chair.txt": "دست‌ها را بالا برده و به وضعیت صندلی بروید.",
    "moves_forwardbendhalfway_to_forwardbenddeep.txt": "یک خم به جلوی عمیق انجام دهید.",
    "moves_forwardbendhalfway_to_fourlimbedstaff_float.txt": "به عقب شناور شوید، از شنای بالا به شنای پایین (چاتورانگا) بروید.",
    "moves_forwardbendhalfway_to_fourlimbedstaff_float_2.txt": "به عقب شناور شوید.",
    "moves_forwardbendhalfway_to_fourlimbedstaff_step_2.txt": "قدم به عقب بگذارید. از شنای بالا به شنای پایین بروید.",
    "moves_forwardbendhalfway_to_fourlimbedstaff_step_3.txt": "به عقب گام بردارید.",
    "moves_forwardbendhalfway_to_fourlimbedstaff_step_l.txt": "پای چپ را به عقب بگذارید؛ پای راست به دنبال آن. از شنای بالا به شنای پایین بروید.",
    "moves_fourlimbedstaff_to_upwarddog.txt": "بچرخید و به وضعیت سگ سر بالا بروید.",
    "moves_headstandtripod_to_headstandtripodkneesonelbows.txt": "با کنترل، زانوهای خود را دوباره روی آرنج‌ها بگذارید.",
    "moves_headstandtripod_to_headstandtripodspirallegs.txt": "اگر آماده هستید، پاها را عریض باز کرده و از سمتی به سمت دیگر بچرخانید.",
    "moves_headstandtripodpreparation_to_headstandtripodkneesonelbows.txt": "یکی یکی، زانوها را روی آرنج‌هایتان بالا بیاورید.",
    "moves_headstandtripodspirallegs_to_headstandtripod.txt": "پاهای خود را به هم بچسبانید.",
    "moves_kneepile_to_boxneutral.txt": "وضعیت زانوها را رها کرده و به حالت چهار دست و پا بروید.",
    "moves_lunge_to_warriori.txt": "دست‌ها را بالا برده و به وضعیت جنگجوی یک بروید.",
    "moves_lungebind_to_chairtwistbind.txt": "با آگاهی پای پشتی را جلو بیاورید تا کنار پای جلویی قرار گیرد.",
    "moves_lungebind_to_chairtwistbind_2.txt": "پای پشتی را به جلو بگذارید.",
    "moves_lungebind_to_lungehandsonmat_2.txt": "دستان خود را روی مت پایین بیاورید.",
    "moves_lungehandsonmat_to_downwarddoglegup_2_l.txt": "پای چپ به سمت بالا کشیده می‌شود.",
    "moves_lungehandsonmat_to_downwarddoglegup_2_r.txt": "پای راست به سمت بالا کشیده می‌شود.",
    "moves_lungehandsonmat_to_downwarddoglegup_l.txt": "پای چپ خود را کاملاً بالا بیاورید.",
    "moves_lungehandsonmat_to_downwarddoglegup_r.txt": "پای راست خود را کاملاً بالا بیاورید.",
    "moves_lungehandsonmat_to_lungehandsonmatback.txt": "لگن را به عقب فشار دهید.",
    "moves_lungehandsonmatback_to_lungehandsonmat.txt": "لگن را به جلو فشار دهید.",
    "moves_lungekneeling_to_forwardbend_l.txt": "پای راست را به جلو قدم بردارید.",
    "moves_lungekneeling_to_forwardbend_r.txt": "پای چپ را به جلو قدم بردارید.",
    "moves_lungekneeling_to_lungekneelingarmforward_l.txt": "دست چپ خود را به جلو بکشید.",
    "moves_lungekneeling_to_lungekneelingarmforward_r.txt": "دست راست خود را به جلو بکشید.",
    "moves_lungekneeling_to_lungekneelingback_l.txt": "پای راست را پایین بیاورید و کاملاً به عقب فشار دهید.",
    "moves_lungekneeling_to_lungekneelingback_r.txt": "پای چپ را پایین بیاورید و کاملاً به عقب فشار دهید.",
    "moves_lungekneeling_to_warriorikneeling.txt": "دست‌ها را بالا بکشید طوری که بازوها کنار گوش‌ها قرار گیرند؛ انگشتان فعال باشند.",
    "moves_lungekneeling_to_warriorikneeling_2.txt": "دست‌ها را به بالا بکشید.",
    "moves_lungekneelingarmforward_to_lungekneelingarmup_r.txt": "دست راست را بالا ببرید و با چشم‌ها انگشتان را دنبال کنید.",
    "moves_lungekneelingarmup_to_lungekneeling_l.txt": "دست چپ خود را پایین بیاورید.",
    "moves_lungekneelingarmup_to_lungekneeling_r.txt": "دست راست خود را پایین بیاورید.",
    "moves_marichiiii_to_boxneutral.txt": "پاهای خود را زیر بدن ضربدری کرده و به وضعیت چهار دست و پا بروید.",
    "moves_mountain_to_mountainarmsup.txt": "هم‌زمان با بالا بردن دست‌ها، انرژی را جمع‌آوری کنید.",
    "moves_mountain_to_mountainarmsup_2.txt": "دست‌ها را بالا ببرید.",
    "moves_mountainarmsup_to_forwardbenddeep.txt": "از مفصل ران خم شوید و به خم به جلوی عمیق بروید.",
    "moves_mountainarmsup_to_mountain.txt": "دستان خود را جلوی قلب پایین بیاورید.",
    "moves_mountainarmsup_to_mountain_2.txt": "دستان جلوی قلب.",
    "moves_pigeonfull_to_kneepile.txt": "پا را رها کرده و به وضعیت زانوی انباشته بروید.",
    "moves_pigeonhalf_to_splitsfront_l.txt": "پای چپ را برای 180 درجه جلو باز کنید.",
    "moves_pigeonhalf_to_splitsfront_r.txt": "پای راست را برای 180 درجه جلو باز کنید.",
    "moves_plank_to_fourlimbedstaff.txt": "از شنای بالا به شنای پایین بروید.",
    "moves_plank_to_fourlimbedstaff_2.txt": "پایین بیایید.",
    "moves_planklegup_to_downwarddogkneetoforehead.txt": "زانو را به سمت پیشانی بیاورید.",
    "moves_planklegup_to_downwarddoglegup.txt": "به بالا فشار دهید.",
    "moves_planklegupkneeling_to_downwarddoglegupkneeling.txt": "به عقب فشار دهید.",
    "moves_plow_to_deafman.txt": "زانوها را خم کرده و به وضعیت ناشنوا بروید.",
    "moves_scale_to_firefly.txt": "به وضعیت کرم شب‌تاب بروید؛ پاها را باز کرده و روی آرنج‌ها تعادل بگیرید.",
    "moves_scale_to_firefly_2.txt": "به وضعیت کرم شب‌تاب بروید.",
    "moves_seatedforwardbend_to_corpse.txt": "انگشتان پا را رها کرده و صاف روی مت دراز بکشید.",
    "moves_seatedonheelshandsonmatopenedknees_to_crow.txt": "زانوها را زیر زیربغل بگذارید و به وضعیت کلاغ بالا بیایید.",
    "moves_seatedonheelsprayer_to_seatedonheelsprayerclosedeyes.txt": "چشمان خود را ببندید و به درون توجه کنید.",
    "moves_seatedonheelsprayer_to_seatedonheelsprayeropenedknees.txt": "زانوها را باز کنید و پاشنه‌ها را به هم نزدیک کنید.",
    "moves_seatedonheelsprayer_to_seatedonheelsprayeropenedknees_2.txt": "زانوهای خود را باز کنید.",
    "moves_seatedonheelsprayerclosedeyes_to_seatedonheelsprayer.txt": "چشمان خود را باز کنید.",
    "moves_seatedonheelsprayeropenedknees_to_seatedonheelshandsonmatopenedknees.txt": "دستان خود را صاف روی زمین بگذارید.",
    "moves_shoulderstandsupported_to_plow_2.txt": "به وضعیت گاوآهن (Plow Pose) بروید.",
    "moves_splitsfront_to_kneepile_l.txt": "پای چپ را به داخل بکشید و بین پاها بنشینید.",
    "moves_splitsfront_to_kneepile_r.txt": "پای راست را به داخل بکشید و بین پاها بنشینید.",
    "moves_splitsstanding_to_forwardbend_l.txt": "پای راست را پایین بیاورید.",
    "moves_splitsstanding_to_forwardbend_r.txt": "پای چپ را پایین بیاورید.",
    "moves_splitswide_to_boxneutral.txt": "پاها را پاشنه-پنجه به داخل جمع کرده و به وضعیت چهار دست و پا بروید.",
    "moves_splitswide_to_forwardbend.txt": "پاها را پاشنه-پنجه به داخل جمع کنید و به جلوی مت بروید.",
    "moves_splitswide_to_headstandtripodpreparation_2.txt": "برای ایستادن روی سر سه پایه آماده شوید.",
    "moves_splitswide_to_tortoise.txt": "پاها را به داخل جمع کنید و به وضعیت لاک‌پشت بروید.",
    "moves_tortoise_to_tortoisebind.txt": "سر را به جلو آورده، دست‌ها را دور بدن بچرخانید و قفل کنید.",
    "moves_tree_to_mountain_l.txt": "با کنترل، به آرامی پای چپ خود را رها کنید.",
    "moves_tree_to_mountain_r.txt": "با کنترل، به آرامی پای راست خود را رها کنید.",
    "moves_triangle_to_triangleforward.txt": "به جلو خم شوید و به وضعیت مثلث بروید.",
    "moves_triangle_to_triangleforward_2.txt": "به جلو خم شوید.",
    "moves_triangle_to_warriorii.txt": "در زانوی جلویی فرو بروید (آن را خم کنید).",
    "moves_triangleforward_to_triangle_2.txt": "بالا بیایید.",
    "moves_triangleforward_to_triangle_l.txt": "اجازه دهید دست راست شما را به بالا بکشد.",
    "moves_triangleforward_to_triangle_r.txt": "اجازه دهید دست چپ شما را به بالا بکشد.",
    "moves_turtle_to_corpse.txt": "روی مت خود پایین بیایید.",
    "moves_upwarddog_to_downwarddog.txt": "به عقب فشار دهید و به سگ سر پایین بروید.",
    "moves_upwarddog_to_downwarddog_pushup.txt": "یک شنا انجام دهید و به عقب فشار دهید.",
    "moves_warriori_to_warriorihandsonhips.txt": "دست‌هایتان را روی لگن بگذارید.",
    "moves_warriori_to_warriorihandssteepled.txt": "دست‌ها را به هم رسانده و انگشتان را در هم قفل کنید.",
    "moves_warriori_to_warriorihandssteepled_2.txt": "انگشتان خود را در هم قفل کنید.",
    "moves_warriori_to_warriorii.txt": "دست‌ها را باز کرده و به وضعیت جنگجوی دو بروید.",
    "moves_warriorihandssteepled_to_warriorihandssteepledforward.txt": "به جلو خم شوید.",
    "moves_warriorihandssteepled_to_warriorihandssteepledforward_2.txt": "به جلو.",
    "moves_warriorihandssteepledforward_to_warriorihandssteepled.txt": "آن را بالا بیاورید.",
    "moves_warriorii_to_fourlimbedstaff.txt": "دست‌ها را چرخشی به پایین آورده، شنای بالا به شنای پایین.",
    "moves_warriorii_to_fourlimbedstaff_2.txt": "چرخشی به پایین بروید.",
    "moves_warriorii_to_plank.txt": "چرخشی به پایین بروید و به وضعیت پلانک برسید.",
    "moves_warriorii_to_plankkneeling.txt": "چرخشی به پایین به پلانک روی زانوها بروید.",
    "moves_warriorii_to_triangle.txt": "پای جلویی خود را صاف کنید.",
    "moves_warriorii_to_warrioriireverse_2.txt": "وضعیت جنگجو را معکوس کنید (جنگجوی معکوس).",
    "moves_warrioriiforward_to_warrioriiforwardarmforward.txt": "دست بالایی را به جلو بکشید و به وضعیت زاویه جانبی بروید.",
    "moves_warrioriireverse_to_warriorii.txt": "به وضعیت جنگجوی ۲ بازگردید.",
    "moves_warrioriireverse_to_warrioriiforward.txt": "آرنج روی زانو.",
    "moves_warriorikneeling_to_forwardbend.txt": "دست‌ها را پایین آورده و پای پشتی را به جلو بگذارید.",
    "moves_warriorikneeling_to_fourlimbedstaff_2.txt": "دست‌ها/بدن را به عقب بکشید.",
    "moves_warriorprayer_to_warriortwist_l.txt": "با بازدم، به سمت چپ بچرخید.",
    "moves_warriorprayer_to_warriortwist_r.txt": "با بازدم، به سمت راست بچرخید.",
    "moves_warriortwist_to_warriortwistextended.txt": "دست‌ها را باز کرده و نگاهتان را به دست بالایی معطوف کنید.",
    "moves_warriortwistextended_to_warriortwist.txt": "دستان خود را به هم متصل کنید.",
    "moves_wheel_to_corpse.txt": "به آرامی روی مت پایین بیایید.",
    "moves_wheel_to_wheellegup_l.txt": "پای چپ را به سمت بالا بکشید.",
    "moves_wheel_to_wheellegup_r.txt": "پای راست را به سمت بالا بکشید.",
    "moves_wheellegup_to_wheel_l.txt": "پای چپ را پایین بیاورید.",
    "moves_wheellegup_to_wheel_r.txt": "پای راست را پایین بیاورید.",
    "moves_boxhandtoankle_to_boxneutral.txt": "آن را به حالت چهار دست و پا بازگردانید.",
    "moves_boxneutral_to_child.txt": "به وضعیت کودک بروید.",
    "moves_boxneutral_to_childwide.txt": "به وضعیت کودک باز بروید.",
    "moves_boxneutral_to_dolphin.txt": "به وضعیت دلفین بالا بروید.",
    "moves_boxneutral_to_downwarddog.txt": "انگشتان پا را جمع کرده و به وضعیت سگ سر پایین بالا بروید.",
    "moves_cat_to_boxneutral.txt": "ستون فقرات را به حالت خنثی برگردانید.",
    "moves_chair_to_chairprayer.txt": "دستان خود را جلوی قلب پایین بیاورید.",
    "moves_chair_to_forwardbenddeep.txt": "دست‌ها را به عقب کشیده و خم به جلوی عمیق انجام دهید.",
    "moves_chairprayer_to_chairtwist_l.txt": "با بازدم، به سمت راست بچرخید.",
    "moves_chairprayer_to_chairtwist_r.txt": "با بازدم، به سمت چپ بچرخید.",
    "moves_chairtwist_to_chairprayer.txt": "دوباره رو به جلو برگردید.",
    "moves_chairtwist_to_chairtwistextended_l.txt": "دست‌ها را به عقب باز کرده و به بالای شانه راست نگاه کنید.",
    "moves_chairtwist_to_chairtwistextended_r.txt": "دست‌ها را به عقب باز کرده و به بالای شانه چپ نگاه کنید.",
    "moves_chairtwistbind_to_chairtwistextended.txt": "قفل دست‌ها را رها کنید.",
    "moves_chairtwistbind_to_lungebind_l.txt": "پای راست را به عقب بگذارید.",
    "moves_chairtwistbind_to_lungebind_r.txt": "پای چپ را به عقب بگذارید.",
    "moves_chairtwistbindup_to_chairtwistbind_l.txt": "با کنترل جاذبه، اجازه دهید پای چپ کاملاً پایین بیاید.",
    "moves_chairtwistbindup_to_chairtwistbind_r.txt": "با کنترل جاذبه، اجازه دهید پای راست کاملاً پایین بیاید.",
    "moves_chairtwistextended_to_chairtwist.txt": "دوباره به وضعیت نیایش بازگردید.",
    "pose_instructions_chair_ins_3.txt": "بازوها کنار گوش‌ها قرار دارند.",
    "pose_instructions_child_wide_side_lean_ins.txt": "پیشانی سنگین روی مت باقی می‌ماند.",
    "pose_instructions_child_wide_side_lean_ins_2.txt": "تنفس اوجایی؛ دم و بازدم از طریق بینی.",
    "pose_instructions_deaf_man_ins_2.txt": "انگشتان شست پا و مچ پاها یکدیگر را لمس می‌کنند.",
    "pose_instructions_dog_ins.txt": "شکم را پایین بیاورید و قفسه سینه را بالا بکشید.",
    "pose_instructions_downward_dog_ins_2.txt": "مطمئن شوید انگشتان کاملاً رو به جلو قرار دارند.",
    "pose_instructions_downward_dog_leg_up_stack_hips_ins.txt": "شانه‌ها موازی با زمین باقی می‌مانند.",
    "pose_instructions_downward_dog_leg_up_stack_hips_ins_2.txt": "بین تیغه‌های شانه رها/پایین شوید.",
    "pose_instructions_downward_dog_on_toes_ins.txt": "قفسه سینه را به سمت ران‌ها فشار دهید.",
    "pose_instructions_feathered_peacock_ins.txt": "بدن خود را در یک خط مستقیم نگه دارید.",
    "pose_instructions_forward_bend_half_way_ins.txt": "ستون فقرات صاف است؛ نوک انگشتان دست هم‌راستا با انگشتان پا هستند.",
    "pose_instructions_forward_bend_half_way_ins_2.txt": "گردن امتداد طبیعی ستون فقرات است.",
    "pose_instructions_mountain_arms_up_ins.txt": "لگن را به داخل جمع کنید و انحنای ملایمی به عقب بدهید.",
    "pose_instructions_savasana_ins.txt": "اگر چیزی برای پوشاندن چشمان خود دارید، استفاده کنید.",
    "pose_instructions_seated_forward_bend_ins.txt": "ستون فقرات خود را صاف نگه دارید.",
    "pose_instructions_seated_on_heels_prayer_closed_eyes_ins.txt": "تعادل خود را به چالش بکشید.",
    "pose_instructions_seated_on_heels_prayer_ins.txt": "دست‌ها در مرکز قلب.",
    "pose_instructions_shoulderstand_supported_ins_2.txt": "پشت گردن صاف روی زمین است.",
    "pose_instructions_splits_wide_ins_2.txt": "دقت کنید هیچ وزنی روی مچ پا یا زانوها وارد نشود.",
    "pose_instructions_splits_wide_ins_3.txt": "لبه‌های بیرونی پاها روی زمین قرار دارند.",
    "pose_instructions_tortoise_ins_2.txt": "پاها با لگن هم‌راستا هستند.",
    "pose_instructions_upward_dog_ins_2.txt": "قلب باز و نگاه آرام است.",
    "pose_instructions_warrior_i_hands_steepled_forward_ins.txt": "بخش پایینی بدن ثابت می‌ماند.",
    "pose_instructions_warrior_i_hands_steepled_forward_ins_2.txt": "بازوها کنار گوش‌ها قرار دارند.",
    "pose_instructions_warrior_i_ins.txt": "بازوهای خود را کنار گوش‌ها نگه دارید.",
    "pose_instructions_warrior_i_ins_2.txt": "لگن را رو به جلو تراز کنید و زانوی پشتی را صاف کنید.",
    "pose_instructions_warrior_i_kneeling_ins.txt": "لگن را به جلو فشار دهید و یک قوس ملایم به عقب بدهید.",
    "pose_instructions_warrior_ii_forward_ins.txt": "زانوی جلویی را در زاویه ۹۰ درجه خم نگه دارید.",
    "pose_instructions_warrior_ii_ins_2.txt": "خط مستقیمی از انرژی از میان دست‌هایتان عبور می‌کند.",
    "pose_instructions_warrior_twist_ins_l.txt": "آرنج راست روی قسمت بیرونی زانوی چپ قرار می‌گیرد.",
    "pose_instructions_warrior_twist_ins_r.txt": "آرنج چپ روی قسمت بیرونی زانوی راست قرار می‌گیرد.",
    "pose_instructions_wheel_ins_2.txt": "انگشتان پا فعال هستند.",
    "pose_names_py_cat.txt": "وضعیت گربه",
    "pose_names_py_chair.txt": "وضعیت صندلی",
    "pose_names_py_child.txt": "وضعیت کودک",
    "pose_names_py_child_wide.txt": "وضعیت کودک باز",
    "pose_names_py_dog.txt": "وضعیت سگ",
    "pose_names_py_downward_dog.txt": "وضعیت سگ سر پایین",
    "pose_names_py_forward_bend.txt": "خم به جلو",
    "pose_names_py_forward_bend_deep.txt": "خم به جلوی عمیق",
    "pose_names_py_forward_bend_half_way.txt": "نیمه‌راه به بالا",
    "pose_names_py_pigeon_half.txt": "به وضعیت نیمه‌کبوتر بروید.",
    "pose_names_py_plank.txt": "وضعیت پلانک",
    "pose_names_py_splits_front.txt": "به وضعیت اسپلیت جلو بروید.",
    "pose_names_py_splits_wide.txt": "به وضعیت اسپلیت باز بروید.",
    "pose_names_py_tree.txt": "وضعیت درخت",
    "pose_names_py_upward_dog.txt": "وضعیت سگ سر بالا",
    "pose_names_py_warrior_i.txt": "جنگجوی یک",
    "pose_names_py_warrior_ii.txt": "جنگجوی دو",
    "pose_names_py_warrior_twist.txt": "جنگجوی پیچان",
    "general_dynamic_state_going_silent.txt": "به همین ترتیب ادامه دهید.",
    "general_exhale.txt": "بازدم.",
    "general_exhale_sound.txt": "بله!",
    "general_for.txt": "چهار.",
    "general_hold.txt": "و نگه دارید.",
    "general_inhale.txt": "دم.",
    "general_inhale_sound.txt": "شما",
    "general_not_found.txt": "با تشکر از تماشای شما!",
    "general_rest.txt": "و استراحت کنید.",
    "general_soften.txt": "و عضلات را رها/نرم کنید."
}

# نام فایل خروجی ZIP
zip_filename = "translated_yoga_files.zip"

# ساخت مستقیم فایل ZIP و درج متون درون آن
with zipfile.ZipFile(zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for filename, content in translations.items():
        zipf.writestr(filename, content.encode('utf-8'))

print(f"فایل زیپ با موفقیت در این مسیر ساخته شد: {zip_filename}")