"""add plans table and verification token expiry

Revision ID: 6bed3763fcf1
Revises: d4892ae57e2c
Create Date: 2026-09-04 02:39:00.207918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bed3763fcf1'
down_revision: Union[str, Sequence[str], None] = 'd4892ae57e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=60), nullable=False),
    sa.Column('price_monthly', sa.Integer(), nullable=False),
    sa.Column('price_yearly', sa.Integer(), nullable=False),
    sa.Column('daily_chart_limit', sa.Integer(), nullable=False),
    sa.Column('can_save_charts', sa.Boolean(), nullable=False),
    sa.Column('can_access_premium', sa.Boolean(), nullable=False),
    sa.Column('premium_paths', sa.Text(), nullable=False),
    sa.Column('features', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    op.add_column('users', sa.Column('verification_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token_expires_at')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
