"""initial schema: users, profiles, charts, yoga, tarot, streaks, settings

Revision ID: d4892ae57e2c
Revises: 
Create Date: 2026-09-04 02:23:09.496967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4892ae57e2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('chart_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chart_type', sa.String(length=30), nullable=False),
    sa.Column('chart_data', sa.JSON(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('interpretation', sa.JSON(), nullable=True),
    sa.Column('aspects_count', sa.Integer(), nullable=True),
    sa.Column('subject_name', sa.Text(), nullable=True),
    sa.Column('person2_name', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chart_history_user_created', 'chart_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chart_history_user_id'), 'chart_history', ['user_id'], unique=False)
    op.create_table('daily_streak',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('streak_type', sa.String(length=30), nullable=False),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('longest_streak', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'streak_type', name='uq_streak_user_type')
    )
    op.create_index(op.f('ix_daily_streak_user_id'), 'daily_streak', ['user_id'], unique=False)
    op.create_table('tarot_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('spread_type', sa.String(length=30), nullable=False),
    sa.Column('card_ids', sa.JSON(), nullable=True),
    sa.Column('reversed', sa.JSON(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tarot_history_user_created', 'tarot_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_tarot_history_user_id'), 'tarot_history', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('birth_month', sa.Integer(), nullable=True),
    sa.Column('birth_day', sa.Integer(), nullable=True),
    sa.Column('birth_hour', sa.Integer(), nullable=True),
    sa.Column('birth_minute', sa.Integer(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.Text(), nullable=True),
    sa.Column('zodiac_type', sa.String(length=20), nullable=True),
    sa.Column('house_system', sa.String(length=20), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'is_default', name='uq_profile_default_per_user')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('user_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_reminder_time', sa.String(length=5), nullable=True),
    sa.Column('default_chart_type', sa.String(length=20), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    op.create_table('yoga_favorites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pose_id', sa.Integer(), nullable=True),
    sa.Column('pose_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pose_id', name='uq_favorite_user_pose')
    )
    op.create_index(op.f('ix_yoga_favorites_user_id'), 'yoga_favorites', ['user_id'], unique=False)
    op.create_table('yoga_practice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pose_id', sa.Integer(), nullable=True),
    sa.Column('pose_name', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('practice_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_yoga_practice_user_date', 'yoga_practice', ['user_id', 'practice_date'], unique=False)
    op.create_index(op.f('ix_yoga_practice_user_id'), 'yoga_practice', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yoga_practice_user_id'), table_name='yoga_practice')
    op.drop_index('ix_yoga_practice_user_date', table_name='yoga_practice')
    op.drop_table('yoga_practice')
    op.drop_index(op.f('ix_yoga_favorites_user_id'), table_name='yoga_favorites')
    op.drop_table('yoga_favorites')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.drop_table('user_settings')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_tarot_history_user_id'), table_name='tarot_history')
    op.drop_index('ix_tarot_history_user_created', table_name='tarot_history')
    op.drop_table('tarot_history')
    op.drop_index(op.f('ix_daily_streak_user_id'), table_name='daily_streak')
    op.drop_table('daily_streak')
    op.drop_index(op.f('ix_chart_history_user_id'), table_name='chart_history')
    op.drop_index('ix_chart_history_user_created', table_name='chart_history')
    op.drop_table('chart_history')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
